
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/cocon/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The target system is: Generic -  - 
      The host system is: Windows - 10.0.26100 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/cocon/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/cocon/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/cocon/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:10 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/msys64/mingw64/bin/avr-gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        C:/Users/cocon/Documents/programming/Portfolio/Firmware/HC-SR04/cmake-build-debug/CMakeFiles/4.0.2/CompilerIdC/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/cocon/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:83 (try_compile)"
      - "C:/Users/cocon/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:10 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/cocon/Documents/programming/Portfolio/Firmware/HC-SR04/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-6o93hy"
      binary: "C:/Users/cocon/Documents/programming/Portfolio/Firmware/HC-SR04/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-6o93hy"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/cocon/Documents/programming/Portfolio/Firmware/HC-SR04/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-6o93hy'
        
        Run Build Command(s): C:/Users/cocon/AppData/Local/Programs/CLion/bin/ninja/win/x64/ninja.exe -v cmTC_dae17
        [1/2] C:\\msys64\\mingw64\\bin\\avr-gcc.exe   -fdiagnostics-color=always   -v -o CMakeFiles/cmTC_dae17.dir/CMakeCCompilerABI.c.obj -c C:/Users/cocon/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeCCompilerABI.c
        Using built-in specs.
        Reading specs from C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/device-specs/specs-avr2
        COLLECT_GCC=C:\\msys64\\mingw64\\bin\\avr-gcc.exe
        Target: avr
        Configured with: ../gcc-15.2.0/configure --prefix=/mingw64 --target=avr --enable-languages=c,c++ --disable-nls --disable-libssp --disable-shared --disable-threads --disable-libgomp --disable-libada --with-dwarf2 --enable-mingw-wildcard
        Thread model: single
        Supported LTO compression algorithms: zlib zstd
        gcc version 15.2.0 (GCC) 
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-v' '-o' 'CMakeFiles/cmTC_dae17.dir/CMakeCCompilerABI.c.obj' '-c' '-mdouble=32' '-mlong-double=64' '-specs=device-specs/specs-avr2' '-dumpdir' 'CMakeFiles/cmTC_dae17.dir/'
         C:/msys64/mingw64/bin/../libexec/gcc/avr/15.2.0/cc1.exe -quiet -v -iprefix C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/ C:/Users/cocon/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeCCompilerABI.c -mn-flash=6 -mskip-bug -quiet -dumpdir CMakeFiles/cmTC_dae17.dir/ -dumpbase CMakeCCompilerABI.c.c -dumpbase-ext .c -mdouble=32 -mlong-double=64 -version -fdiagnostics-color=always -o C:\\Users\\cocon\\AppData\\Local\\Temp\\ccYxWAYK.s
        GNU C23 (GCC) version 15.2.0 (avr)
        	compiled by GNU C version 15.2.0, GMP version 6.3.0, MPFR version 4.2.2, MPC version 1.3.1, isl version isl-0.27-GMP
        
        GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
        ignoring nonexistent directory "C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/../../../../avr/sys-include"
        ignoring duplicate directory "C:/msys64/mingw64/lib/gcc/../../lib/gcc/avr/15.2.0/include"
        ignoring duplicate directory "C:/msys64/mingw64/lib/gcc/../../lib/gcc/avr/15.2.0/include-fixed"
        ignoring nonexistent directory "C:/msys64/mingw64/lib/gcc/../../lib/gcc/avr/15.2.0/../../../../avr/sys-include"
        ignoring duplicate directory "C:/msys64/mingw64/lib/gcc/../../lib/gcc/avr/15.2.0/../../../../avr/include"
        #include "..." search starts here:
        #include <...> search starts here:
         C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/include
         C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/include-fixed
         C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/../../../../avr/include
        End of search list.
        Compiler executable checksum: 064de731fb2cfb15d4d0204b11c57b97
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-v' '-o' 'CMakeFiles/cmTC_dae17.dir/CMakeCCompilerABI.c.obj' '-c' '-mdouble=32' '-mlong-double=64' '-specs=device-specs/specs-avr2' '-dumpdir' 'CMakeFiles/cmTC_dae17.dir/'
         C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/../../../../avr/bin/as.exe -mmcu=avr2 -mgcc-isr -o CMakeFiles/cmTC_dae17.dir/CMakeCCompilerABI.c.obj C:\\Users\\cocon\\AppData\\Local\\Temp\\ccYxWAYK.s
        COMPILER_PATH=C:/msys64/mingw64/bin/../libexec/gcc/avr/15.2.0/;C:/msys64/mingw64/bin/../libexec/gcc/;C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/../../../../avr/bin/
        LIBRARY_PATH=C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/;C:/msys64/mingw64/bin/../lib/gcc/;C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/../../../../avr/lib/
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-v' '-o' 'CMakeFiles/cmTC_dae17.dir/CMakeCCompilerABI.c.obj' '-c' '-mdouble=32' '-mlong-double=64' '-specs=device-specs/specs-avr2' '-dumpdir' 'CMakeFiles/cmTC_dae17.dir/CMakeCCompilerABI.c.'\x0d
        [2/2] C:\\WINDOWS\\system32\\cmd.exe /C "cd . && C:\\Users\\cocon\\AppData\\Local\\Programs\\CLion\\bin\\cmake\\win\\x64\\bin\\cmake.exe -E rm -f libcmTC_dae17.a && C:\\msys64\\mingw64\\bin\\avr-ar.exe qc libcmTC_dae17.a  CMakeFiles/cmTC_dae17.dir/CMakeCCompilerABI.c.obj && C:\\msys64\\mingw64\\bin\\avr-ranlib.exe libcmTC_dae17.a && cd ."
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/cocon/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:191 (message)"
      - "C:/Users/cocon/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:10 (project)"
    message: |
      Parsed C implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/include]
          add: [C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/include-fixed]
          add: [C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/../../../../avr/include]
        end of search list found
        collapse include dir [C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/include] ==> [C:/msys64/mingw64/lib/gcc/avr/15.2.0/include]
        collapse include dir [C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/include-fixed] ==> [C:/msys64/mingw64/lib/gcc/avr/15.2.0/include-fixed]
        collapse include dir [C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/../../../../avr/include] ==> [C:/msys64/mingw64/avr/include]
        implicit include dirs: [C:/msys64/mingw64/lib/gcc/avr/15.2.0/include;C:/msys64/mingw64/lib/gcc/avr/15.2.0/include-fixed;C:/msys64/mingw64/avr/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/cocon/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:227 (message)"
      - "C:/Users/cocon/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:10 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)))("|,| |$)]
        ignore line: [Change Dir: 'C:/Users/cocon/Documents/programming/Portfolio/Firmware/HC-SR04/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-6o93hy']
        ignore line: []
        ignore line: [Run Build Command(s): C:/Users/cocon/AppData/Local/Programs/CLion/bin/ninja/win/x64/ninja.exe -v cmTC_dae17]
        ignore line: [[1/2] C:\\msys64\\mingw64\\bin\\avr-gcc.exe   -fdiagnostics-color=always   -v -o CMakeFiles/cmTC_dae17.dir/CMakeCCompilerABI.c.obj -c C:/Users/cocon/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeCCompilerABI.c]
        ignore line: [Using built-in specs.]
        ignore line: [Reading specs from C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/device-specs/specs-avr2]
        ignore line: [COLLECT_GCC=C:\\msys64\\mingw64\\bin\\avr-gcc.exe]
        ignore line: [Target: avr]
        ignore line: [Configured with: ../gcc-15.2.0/configure --prefix=/mingw64 --target=avr --enable-languages=c c++ --disable-nls --disable-libssp --disable-shared --disable-threads --disable-libgomp --disable-libada --with-dwarf2 --enable-mingw-wildcard]
        ignore line: [Thread model: single]
        ignore line: [Supported LTO compression algorithms: zlib zstd]
        ignore line: [gcc version 15.2.0 (GCC) ]
        ignore line: [COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-v' '-o' 'CMakeFiles/cmTC_dae17.dir/CMakeCCompilerABI.c.obj' '-c' '-mdouble=32' '-mlong-double=64' '-specs=device-specs/specs-avr2' '-dumpdir' 'CMakeFiles/cmTC_dae17.dir/']
        ignore line: [ C:/msys64/mingw64/bin/../libexec/gcc/avr/15.2.0/cc1.exe -quiet -v -iprefix C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/ C:/Users/cocon/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeCCompilerABI.c -mn-flash=6 -mskip-bug -quiet -dumpdir CMakeFiles/cmTC_dae17.dir/ -dumpbase CMakeCCompilerABI.c.c -dumpbase-ext .c -mdouble=32 -mlong-double=64 -version -fdiagnostics-color=always -o C:\\Users\\cocon\\AppData\\Local\\Temp\\ccYxWAYK.s]
        ignore line: [GNU C23 (GCC) version 15.2.0 (avr)]
        ignore line: [	compiled by GNU C version 15.2.0  GMP version 6.3.0  MPFR version 4.2.2  MPC version 1.3.1  isl version isl-0.27-GMP]
        ignore line: []
        ignore line: [GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072]
        ignore line: [ignoring nonexistent directory "C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/../../../../avr/sys-include"]
        ignore line: [ignoring duplicate directory "C:/msys64/mingw64/lib/gcc/../../lib/gcc/avr/15.2.0/include"]
        ignore line: [ignoring duplicate directory "C:/msys64/mingw64/lib/gcc/../../lib/gcc/avr/15.2.0/include-fixed"]
        ignore line: [ignoring nonexistent directory "C:/msys64/mingw64/lib/gcc/../../lib/gcc/avr/15.2.0/../../../../avr/sys-include"]
        ignore line: [ignoring duplicate directory "C:/msys64/mingw64/lib/gcc/../../lib/gcc/avr/15.2.0/../../../../avr/include"]
        ignore line: [#include "..." search starts here:]
        ignore line: [#include <...> search starts here:]
        ignore line: [ C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/include]
        ignore line: [ C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/include-fixed]
        ignore line: [ C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/../../../../avr/include]
        ignore line: [End of search list.]
        ignore line: [Compiler executable checksum: 064de731fb2cfb15d4d0204b11c57b97]
        ignore line: [COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-v' '-o' 'CMakeFiles/cmTC_dae17.dir/CMakeCCompilerABI.c.obj' '-c' '-mdouble=32' '-mlong-double=64' '-specs=device-specs/specs-avr2' '-dumpdir' 'CMakeFiles/cmTC_dae17.dir/']
        ignore line: [ C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/../../../../avr/bin/as.exe -mmcu=avr2 -mgcc-isr -o CMakeFiles/cmTC_dae17.dir/CMakeCCompilerABI.c.obj C:\\Users\\cocon\\AppData\\Local\\Temp\\ccYxWAYK.s]
        ignore line: [COMPILER_PATH=C:/msys64/mingw64/bin/../libexec/gcc/avr/15.2.0/]
        ignore line: [C:/msys64/mingw64/bin/../libexec/gcc/]
        ignore line: [C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/../../../../avr/bin/]
        ignore line: [LIBRARY_PATH=C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/]
        ignore line: [C:/msys64/mingw64/bin/../lib/gcc/]
        ignore line: [C:/msys64/mingw64/bin/../lib/gcc/avr/15.2.0/../../../../avr/lib/]
        ignore line: [COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-v' '-o' 'CMakeFiles/cmTC_dae17.dir/CMakeCCompilerABI.c.obj' '-c' '-mdouble=32' '-mlong-double=64' '-specs=device-specs/specs-avr2' '-dumpdir' 'CMakeFiles/cmTC_dae17.dir/CMakeCCompilerABI.c.'\x0d]
        ignore line: [[2/2] C:\\WINDOWS\\system32\\cmd.exe /C "cd . && C:\\Users\\cocon\\AppData\\Local\\Programs\\CLion\\bin\\cmake\\win\\x64\\bin\\cmake.exe -E rm -f libcmTC_dae17.a && C:\\msys64\\mingw64\\bin\\avr-ar.exe qc libcmTC_dae17.a  CMakeFiles/cmTC_dae17.dir/CMakeCCompilerABI.c.obj && C:\\msys64\\mingw64\\bin\\avr-ranlib.exe libcmTC_dae17.a && cd ."]
        ignore line: []
        ignore line: []
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
...
